import importlib.metadata as _metadata

from civitapy.client import AsyncPaginator, CivitAIClient
from civitapy.enums import (
    ArticleSortOrder,
    Availability,
    AvatarNSFWLevel,
    BaseModel,
    BaseModelType,
    CheckpointType,
    CollectionSortOrder,
    ImageSortOrder,
    MediaType,
    ModelFileType,
    ModelType,
    ModelVersionStatus,
    ModerationMode,
    NSFWLevel,
    Period,
    SortOrder,
    UserStatus,
    UserTier,
    VaultSortOrder,
    VaultStatus,
)
from civitapy.errors import (
    CivitAIAuthError,
    CivitAIBadRequestError,
    CivitAIDownloadError,
    CivitAIError,
    CivitAIForbiddenError,
    CivitAINotFoundError,
    CivitAIRateLimitError,
    CivitAIServerError,
)
from civitapy.models import (
    Article,
    ArticleStats,
    ArticleTag,
    CivitaiResourceRef,
    Collection,
    CoverImage,
    Creator,
    CurrentUser,
    FullModelFile,
    HashLookupResult,
    Image,
    ImageMeta,
    ImageStats,
    MiniHashes,
    MiniModelFile,
    MiniModelVersion,
    Model,
    ModelFileHashes,
    ModelFileMetadata,
    ModelVersion,
    ModelVersionFile,
    ModelVersionSummary,
    Stats,
    TagItem,
    UserLite,
    UserSummary,
    VaultInfo,
    VaultItem,
    VaultToggleResponse,
    VersionStats,
)

__version__ = _metadata.version("civitapy")

__all__ = [  # noqa: RUF022
    # Client
    "CivitAIClient",
    "AsyncPaginator",
    # Package metadata
    "__version__",
    # Enums
    "ModelType",
    "ModelFileType",
    "BaseModel",
    "BaseModelType",
    "SortOrder",
    "ImageSortOrder",
    "ArticleSortOrder",
    "CollectionSortOrder",
    "VaultSortOrder",
    "Period",
    "CheckpointType",
    "MediaType",
    "NSFWLevel",
    "UserTier",
    "UserStatus",
    "ModelVersionStatus",
    "Availability",
    "ModerationMode",
    "VaultStatus",
    "AvatarNSFWLevel",
    # Models
    "Stats",
    "UserSummary",
    "ModelFileHashes",
    "ModelFileMetadata",
    "ModelVersionFile",
    "VersionStats",
    "Model",
    "ModelVersionSummary",
    "ModelVersion",
    "FullModelFile",
    "MiniHashes",
    "MiniModelFile",
    "MiniModelVersion",
    "HashLookupResult",
    "ImageStats",
    "CivitaiResourceRef",
    "ImageMeta",
    "Image",
    "ArticleTag",
    "CoverImage",
    "ArticleStats",
    "Article",
    "Collection",
    "Creator",
    "TagItem",
    "UserLite",
    "CurrentUser",
    "VaultInfo",
    "VaultItem",
    "VaultToggleResponse",
    # Errors
    "CivitAIError",
    "CivitAIAuthError",
    "CivitAIRateLimitError",
    "CivitAINotFoundError",
    "CivitAIBadRequestError",
    "CivitAIForbiddenError",
    "CivitAIServerError",
    "CivitAIDownloadError",
]
